server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d85n17jeo5us73bhg3ig-a:5432/platzi_play_db_q9bl?sslmode=require
spring.datasource.username=nayarith
spring.datasource.password=GAIIioETsEXr1pybb3GDqAIQORVK56ni
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode= always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

langchain4j.open-ai.chat-model.api-key=demo




