#spring.profiles.active=dev
spring.profiles.active=prod

spring.application.name=alejandro play
server.servlet.context-path=/platzi-play/api

#postgrestsql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

debug=true



